services:
  - type: web
    name: hoshang-portfolio
    runtime: static
    rootDir: frontend
    buildCommand: yarn install --frozen-lockfile && yarn build
    staticPublishPath: build
    pullRequestPreviewsEnabled: true
    headers:
      - path: /static/*
        name: Cache-Control
        value: public, max-age=31536000, immutable
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
